import { food } from "./app/shared/model/food";

export const sample_foods:food[]=[
  {
  id : '1',
  name: 'pizza pepperoni',
  cooktime:'10-15',
  favorite:false,
  origins:['italy'],
  stars:4,
  imageUrl: 'assets/food-1.jpg',
  price:10,
  tags: ['fastfood','pizza','lunch'],

  },
  {
    id : '2',
    name: 'meatball',
    cooktime:'20-35',
    favorite:true,
    origins:['persia','middle east','asia'],
    stars:4.5,
    imageUrl: 'assets/food-2.jpg',
    price:25,
    tags: ['slowfood','lunch'],
  },
  {

    id:'3',
    name: 'Hamburger',
    price: 5,
    cooktime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cooktime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cooktime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cooktime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 12,
    cooktime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 9,
    cooktime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]


